### ISSUE TITLE
Multiple Choice formatting

### ISSUE THREAD

**Issue by planius** [awsmug/Questions#15]
Hi, I am trying to set up a multiple choice survey, which works fine, but the displayed formatting seems really odd - the tick boxes are centered instead of being on the right and they are aligned to top in each row, not to the middle. Not sure if this is a bug or a feature. Survey can be viewed at: 
http://www.leadershipmastery.com.au/survey/new-product-development-survey/

![survey1](https://cloud.githubusercontent.com/assets/4189683/8759610/3e347500-2d3b-11e5-9308-93748cf788d0.JPG)
![survey2](https://cloud.githubusercontent.com/assets/4189683/8759613/451d945a-2d3b-11e5-893c-71d58750aa06.JPG)

**Comment by mahype** [comment]
Hi Planius,

the problem is the CSS of your theme in line 322.
http://www.leadershipmastery.com.au/wp-content/themes/executive-pro/style.css?ver=3.0.0

There you have defined 100% width for 
<code>
input, select, textarea {
   ...
    width: 100%;
}
</code>

You have to overwrite or replace the width for it with "auto". Like here:

<code>
input, select, textarea {
   ...
    width:auto;
}
</code>

After that the checkboxes will stand at the left side.

I did it and it looked like this:
![new_product_development_survey_ _leadership_mastery_-_2015-07-20_10 28 16](https://cloud.githubusercontent.com/assets/663697/8772169/145f726c-2eca-11e5-97df-bb8ae233b523.png)

Greetings,

Sven

**Comment by planius** [comment]
Thanks Sven,

much appreciated. I had no idea where to look.

Cheers
Peter

**Comment by mahype** [comment]
You're welcome :)
